# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Unpause' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Unpause
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
    pod 'SnapKit', '~> 5.0.0'
    pod 'Firebase/Core'
    pod 'Firebase/Firestore'
    pod 'Firebase/Analytics'
    pod 'Firebase/Auth'
    pod 'GoogleSignIn'
    pod 'RxKeyboard'
    pod "RxGesture"
    pod 'RxFirebase/Firestore'
    pod 'RxFirebase/RemoteConfig'
    pod 'RxFirebase/Database'
    pod 'RxFirebase/Storage'
    pod 'RxFirebase/Auth'
    pod 'RxFirebase/Functions'
    pod 'DifferenceKit'
    pod 'SwiftyStoreKit'
    pod 'SwiftyBeaver'
    pod 'Charts'
    pod 'SwiftLint'
    
    
    target 'UnpauseTests' do
        inherit! :search_paths
        pod 'RxTest'
    end
end
